{% set name = "cassandra-driver" %}
{% set version = "3.29.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/datastax/python-{{ name.split('-')[1] }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: aa3be5396e05b395c178091656a329daba23b0d4dd69b8d076090157f86e6d13

build:
  # Python version limited based on documentation and cython availability up to python 3.12
  skip: true  # [py<38 or py>312]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - wheel
    - setuptools
    - cython >=0.20,!=0.25,<0.30
    - libev  # [not win]
  run:
    - python
    - numpy
    - geomet >=0.1,<0.3
    - libev  # [not win]
  run_constrained:
    - gremlinpython >=3.4.6
    - cryptography >=35.0

# Skip due to missing dependencies (puresasl and pyximport).
# Also, don't run integration tests because they require
# Cassandra Cluster Manager to be running (no such dependency).
{% set unit_tests_to_skip = [
    "tests/unit/advanced/test_auth.py",
    "tests/unit/cython/test_bytesio.py",
    "tests/unit/cython/test_types.py",
    "tests/unit/cython/test_utils.py"
] %}

test:
  imports:
    - cassandra
    - cassandra.io
    - cassandra.cqlengine
    - cassandra.graph
    - cassandra.datastax
    - cassandra.datastax.insights
    - cassandra.datastax.graph
    - cassandra.datastax.graph.fluent
    - cassandra.datastax.cloud
    - cassandra.column_encryption
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - eventlet
  commands:
    - pip check
    - python -c "import cassandra; print(cassandra.__version__)"
    # For Windows, skip as well a test that overflows timestamp limits for this OS. Also,
    # limit testing up to python 3.11 as it fails on python 3.12 due to asyncio changes
    # and libev requirement.
    # For OSX, skip as well a test that fails ocasionally with python 3.9.
    - pytest -v tests/unit {% for skip in unit_tests_to_skip %}--ignore={{ skip }} {% endfor %} # [linux]
    - pytest -v tests/unit {% for skip in unit_tests_to_skip %}--ignore={{ skip }} {% endfor %} -k "not test_empty_connections" # [osx]
    - pytest -v tests/unit {% for skip in unit_tests_to_skip %}--ignore={{ skip }} {% endfor %} -k "not test_deserialize_date_range_year" # [win and py<312]

about:
  home: https://github.com/datastax/python-driver
  license:  Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: DataStax Driver for Apache Cassandra
  description: |
    A modern, feature-rich and highly-tunable Python client library for Apache Cassandra (2.1+)
    and DataStax Enterprise (4.7+) using exclusively Cassandra's binary protocol and
    Cassandra Query Language v3.
  doc_url: https://docs.datastax.com/en/developer/python-driver/3.29/index.html
  dev_url: https://github.com/datastax/python-driver/tree/3.29.2

extra:
  recipe-maintainers:
    - petercable
    - anirrudh
    - scopatz
