travis:
  secure:
    BINSTAR_TOKEN: H3xegiruOe0j2hJYi+fDO4tvblkLXLSgBKbk7bF0AGieDpvTsOgEshPC7G5RG+yFvBsKGAEolPejnls2CqKJoKcWTZTRedkURmsUUeYOAVXMtAtZ7G4t+FGJnB23ax4ImBx472xDbxssAGAAa0nUJbnm5PqQt+kRVidHSZsR8cI1hPvX/q4i/FkZGX2NZA8jFgOGZN8JqqARsfow23hjgScx5rNjIkEA7p/6fIdXj+AEFAX1x0tV9VYewzXsgTDSclgVP2PDz5HBPlvDIF26xDOx6y3GxwAtlmvOKzdCyNQ5mQ6G23kBg6vxqGDyx7tXVSczw7iX3PfOdB57jrA+1BEFvAQ6BEKL345JGznOYX2HJ/VgFNRopK/SSYCQSU8Vn2UUAeD132eDSK9ajj2ppM6SPi3VrEHHE8IGRgFQ9HuNSUtGNwCiPpv2E1jQnYfh9VW2G0cHBzhS8apZ4s4CvSiVoeb1cjkXtgmii3r1T4sP1jQrVQIqVb5o7GW02NcBKlfRqL9W8OfoH+vkyfmjHd+zrR0C1zZgBvzXWE2gYGX9uTvf/AncWsUPpaTBLzzZ38eI42gwaWr8AJ5gQbrttL2BD79xZrLfd3n7X0EIJfQWmQzCHkeuiSHmF6SWsY2dKPBoJh1a4oCGZOkNgu6nvsBPhlhnL60LVSM/k+ofU9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
