travis:
  secure:
    BINSTAR_TOKEN: CXQJHyUJY/YxfR/fzLDtUJWgafIjTrwxEIQzqfp32ql5TBxtQAZ/Wm9RKu9XHecLTjQBZqI4Oe5mUroAbpvIcYAxLW5kCWsOpnuk2TuYuX5ZWWYxnMfLaj8sSKevhFvTdqL/soRsOIUkpw1RHAFHWaTxoJq/WHIRWuuHHb/uCRzDZs/BqZlsFl8jDsHQfPw8NIqozGKzFGHd6fpdE/hd9az4u/Vz8luprv4wTGKFx+J+Sw8o585U+TjVTd27gK58rfZxNeXV9BgRuYh/d8j2GipAGAbuOaTCdsaVPU+VrIHyZwVgHz5psOqi3TR7vS9t/Z+wrN4JO4mrB/e7Urf7Axjz5DMZ4lFd7Ld1O2ExT+JIiPK0ZefMpnI9bEGBh6jP4nHww4gtwcByNr9OnzA6/EHyXMVFw/wen5csqNXFvrGovekHChk3zNZuaxIJHgcZeA+Mw8LmLoRxbydwFmfYHMi8T4JkQx6uq9m/QoWknSDvotcejltAm4YjdAWYnF+jGlww8xAZA0PtVoj7ClJQDlI1/RdRhHL1F+YUm0Dl08AFGZtyPli37rKK4Hr/JX7ctoxNtkg+ete6MypK86VT19EvzJ++912GsY5AM0vxRJcrM7dsIG4NTqYkQp2gTK1vF2/JV0kTWemXBBlZz8CnhT8fOqQxa42U2Ne83bwppfc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
